### ISSUE TITLE
Version doesn't actually default to latest

### ISSUE THREAD

**Issue by elibosley** [dsaltares/fetch-gh-release-asset#50] opened 2022-09-14 18:17 UTC
In the readme it says: 

```
# version

The release version to fetch from in the form tags/<tag_name> or <release_id>. Defaults to latest.
```

But from reading the code and my own testing it doesn't actually default to using latest. Maybe just update readme to say that latest is an option but not that it defaults to that? 

Btw I love this workflow thank you for making this!

**Comment by dsaltares** [comment] 2023-04-20 13:56
I think the problem is that the value of `version` doesn't actually default to latest:

```ts
const version = core.getInput('version', { required: false });

const getRelease = (
  octokit: ReturnType<typeof github.getOctokit>,
  { owner, repo, version }: GetReleaseOptions
) => {
  const tagsMatch = version.match(/^tags\/(.*)$/);
  if (version === 'latest') {
    return octokit.rest.repos.getLatestRelease({ owner, repo });
  } else if (tagsMatch !== null && tagsMatch[1]) {
    return octokit.rest.repos.getReleaseByTag({
      owner,
      repo,
      tag: tagsMatch[1],
    });
  } else {
    return octokit.rest.repos.getRelease({
      owner,
      repo,
      release_id: Math.trunc(Number(version)),
    });
  }
};
```

By changing it to 

```ts
const version = core.getInput('version', { required: false }) || 'latest';
```

It should actually fetch the latest (chronologically speaking) version released when the `version` parameter is not present.

**Comment by dsaltares** [comment] 2023-04-20 14:08
This is now fixed if you point your job to `master`.

**Closed** 2023-04-20 14:08 UTC

**Comment by dsaltares** [comment] 2023-04-24 08:11
New version with this fix released https://github.com/dsaltares/fetch-gh-release-asset/releases/tag/1.1.1
