### ISSUE TITLE
latest commit broke my build

### ISSUE THREAD

**Issue by steveklabnik** [dsaltares/fetch-gh-release-asset#39] opened 2022-04-19 16:31 UTC
Example of the failure: https://github.com/oxidecomputer/hubris/pull/505

TL;DR: apparently a release named "nightly" is a "malformed version" after https://github.com/dsaltares/fetch-gh-release-asset/pull/36 landed.

I haven't taken the time to investigate exactly why yet, but figured I should let you know! We've pinned to 0.0.8 in the meantime.

**Comment by dsaltares** [comment] 2022-04-19 16:55
I think this is a duplicate of #38. Thanks for reporting. Glad you could just pin to the previous release.

**Closed by dsaltares** 2022-04-19 16:55 UTC
